window.esdocSearchIndex = [
  [
    "isomorphic-react-redux-router/src/client/utilities.js~$",
    "variable/index.html#static-variable-$",
    "<span>$</span> <span class=\"search-result-import-path\">isomorphic-react-redux-router/src/client/utilities.js</span>",
    "variable"
  ],
  [
    "isomorphic-react-redux-router/src/components/app.js~app",
    "class/src/components/App.js~App.html",
    "<span>App</span> <span class=\"search-result-import-path\">isomorphic-react-redux-router/src/components/App.js</span>",
    "class"
  ],
  [
    "isomorphic-react-redux-router/src/config.js~env",
    "variable/index.html#static-variable-ENV",
    "<span>ENV</span> <span class=\"search-result-import-path\">isomorphic-react-redux-router/src/config.js</span>",
    "variable"
  ],
  [
    "isomorphic-react-redux-router/src/actiontypes.js~item",
    "variable/index.html#static-variable-ITEM",
    "<span>ITEM</span> <span class=\"search-result-import-path\">isomorphic-react-redux-router/src/actionTypes.js</span>",
    "variable"
  ],
  [
    "isomorphic-react-redux-router/src/components/item.js~item",
    "class/src/components/Item.js~Item.html",
    "<span>Item</span> <span class=\"search-result-import-path\">isomorphic-react-redux-router/src/components/Item.js</span>",
    "class"
  ],
  [
    "isomorphic-react-redux-router/src/config.js~server_root",
    "variable/index.html#static-variable-SERVER_ROOT",
    "<span>SERVER_ROOT</span> <span class=\"search-result-import-path\">isomorphic-react-redux-router/src/config.js</span>",
    "variable"
  ],
  [
    "isomorphic-react-redux-router/src/server/app.js~app",
    "variable/index.html#static-variable-app",
    "<span>app</span> <span class=\"search-result-import-path\">isomorphic-react-redux-router/src/server/app.js</span>",
    "variable"
  ],
  [
    "isomorphic-react-redux-router/src/utilities.js~constjoin",
    "variable/index.html#static-variable-constJoin",
    "<span>constJoin</span> <span class=\"search-result-import-path\">isomorphic-react-redux-router/src/utilities.js</span>",
    "variable"
  ],
  [
    "isomorphic-react-redux-router/src/utilities.js~decodestore",
    "variable/index.html#static-variable-decodeStore",
    "<span>decodeStore</span> <span class=\"search-result-import-path\">isomorphic-react-redux-router/src/utilities.js</span>",
    "variable"
  ],
  [
    "isomorphic-react-redux-router/src/actions/factories.js~listactionfactory",
    "variable/index.html#static-variable-listActionFactory",
    "<span>listActionFactory</span> <span class=\"search-result-import-path\">isomorphic-react-redux-router/src/actions/factories.js</span>",
    "variable"
  ],
  [
    "isomorphic-react-redux-router/src/reducers/factories.js~listreducerfactory",
    "variable/index.html#static-variable-listReducerFactory",
    "<span>listReducerFactory</span> <span class=\"search-result-import-path\">isomorphic-react-redux-router/src/reducers/factories.js</span>",
    "variable"
  ],
  [
    "isomorphic-react-redux-router/src/utilities.js~log",
    "variable/index.html#static-variable-log",
    "<span>log</span> <span class=\"search-result-import-path\">isomorphic-react-redux-router/src/utilities.js</span>",
    "variable"
  ],
  [
    "isomorphic-react-redux-router/src/utilities.js~pelay",
    "variable/index.html#static-variable-pelay",
    "<span>pelay</span> <span class=\"search-result-import-path\">isomorphic-react-redux-router/src/utilities.js</span>",
    "variable"
  ],
  [
    "isomorphic-react-redux-router/src/server/utilities.js~prawn",
    "variable/index.html#static-variable-prawn",
    "<span>prawn</span> <span class=\"search-result-import-path\">isomorphic-react-redux-router/src/server/utilities.js</span>",
    "variable"
  ],
  [
    "isomorphic-react-redux-router/src/server/utilities.js~spawnemon",
    "variable/index.html#static-variable-spawnemon",
    "<span>spawnemon</span> <span class=\"search-result-import-path\">isomorphic-react-redux-router/src/server/utilities.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/actiontypes.js",
    "file/src/actionTypes.js.html",
    "src/actionTypes.js",
    "file"
  ],
  [
    "src/actions/factories.js",
    "file/src/actions/factories.js.html",
    "src/actions/factories.js",
    "file"
  ],
  [
    "src/actions/index.js",
    "file/src/actions/index.js.html",
    "src/actions/index.js",
    "file"
  ],
  [
    "src/actions/item.js",
    "file/src/actions/item.js.html",
    "src/actions/item.js",
    "file"
  ],
  [
    "src/client/index.js",
    "file/src/client/index.js.html",
    "src/client/index.js",
    "file"
  ],
  [
    "src/client/utilities.js",
    "file/src/client/utilities.js.html",
    "src/client/utilities.js",
    "file"
  ],
  [
    "src/components/app.js",
    "file/src/components/App.js.html",
    "src/components/App.js",
    "file"
  ],
  [
    "src/components/app.js~app#handleclick",
    "class/src/components/App.js~App.html#instance-method-handleClick",
    "src/components/App.js~App#handleClick",
    "method"
  ],
  [
    "src/components/app.js~app#render",
    "class/src/components/App.js~App.html#instance-method-render",
    "src/components/App.js~App#render",
    "method"
  ],
  [
    "src/components/item.js",
    "file/src/components/Item.js.html",
    "src/components/Item.js",
    "file"
  ],
  [
    "src/components/item.js~item#render",
    "class/src/components/Item.js~Item.html#instance-method-render",
    "src/components/Item.js~Item#render",
    "method"
  ],
  [
    "src/components/itemlist.js",
    "file/src/components/ItemList.js.html",
    "src/components/ItemList.js",
    "file"
  ],
  [
    "src/components/index.js",
    "file/src/components/index.js.html",
    "src/components/index.js",
    "file"
  ],
  [
    "src/config.js",
    "file/src/config.js.html",
    "src/config.js",
    "file"
  ],
  [
    "src/reducers/factories.js",
    "file/src/reducers/factories.js.html",
    "src/reducers/factories.js",
    "file"
  ],
  [
    "src/reducers/index.js",
    "file/src/reducers/index.js.html",
    "src/reducers/index.js",
    "file"
  ],
  [
    "src/reducers/items.js",
    "file/src/reducers/items.js.html",
    "src/reducers/items.js",
    "file"
  ],
  [
    "src/routes/index.js",
    "file/src/routes/index.js.html",
    "src/routes/index.js",
    "file"
  ],
  [
    "src/server/app.js",
    "file/src/server/app.js.html",
    "src/server/app.js",
    "file"
  ],
  [
    "src/server/devserver.js",
    "file/src/server/devServer.js.html",
    "src/server/devServer.js",
    "file"
  ],
  [
    "src/server/index.js",
    "file/src/server/index.js.html",
    "src/server/index.js",
    "file"
  ],
  [
    "src/server/utilities.js",
    "file/src/server/utilities.js.html",
    "src/server/utilities.js",
    "file"
  ],
  [
    "src/test/utilities.js",
    "file/src/test/utilities.js.html",
    "src/test/utilities.js",
    "file"
  ],
  [
    "src/utilities.js",
    "file/src/utilities.js.html",
    "src/utilities.js",
    "file"
  ]
]